
highlighter: rouge
permalink: pretty
markdown: kramdown


title: Chris Soliday
email: solidaycl+web@gmail.com
description: >-
  Chris on the web.
url: ""
github_username:  solidaycl

plugins:
    - jekyll-redirect-from
    - jekyll-mentions
    - jekyll-feed


feed:
    path: news.xml

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - vendor/
    - sponsor-generator/
